### ISSUE TITLE
本地部署报错：请求失败怎么解决呢？

### ISSUE THREAD

**Issue by lys0214** [ourongxing/chatgpt-vercel#100]
![image](https://user-images.githubusercontent.com/68138841/226306025-35b77c55-4b08-44a7-a221-30805446608f.png)
![image](https://user-images.githubusercontent.com/68138841/226306093-812dc8f3-c7db-4073-af56-21b1b462e275.png)

**Comment by ourongxing** [comment]
api 被墙，自己开代理
