### ISSUE TITLE
vercel 修改环境变量 `defaultSetting` 重新部署后不生效

### ISSUE THREAD

**Issue by GOWxx** [ourongxing/chatgpt-vercel#104]
变量 `parsed` 来自于  `localStorage.getItem("setting")`，且会覆盖 `defaultSetting`。
上一次使用网站在 `localStorage` 里留下的数据，网站重新部署后，重新打开网站也会由 `localStorage` 里的数据优先。
用户可以清除  `localStorage` 里的数据或正常使用产生新的 `setting` 数据，不过可能重新部署时如果遇到这个 bug 会困惑下。
也可由开发者在 `Main.tsx` 中加入 `onCleanup` 在组件销毁时清除 `setting` 。

https://github.com/ourongxing/chatgpt-vercel/blob/b7ee5814e0d4c53a04146c48abc00e448349a8c4/src/components/Main.tsx#L84-L96

**Comment by ourongxing** [comment]
逻辑就是这个逻辑，总不能用户改了设置，你还可以继续修改用户的设置。
