### ISSUE TITLE
填入key无效

### ISSUE THREAD

**Issue by enron2014** [ourongxing/chatgpt-vercel#109]
一键点击deploy的时候，输入key，但是始终无效
![Screenshot_20230322_003042_com microsoft emmx](https://user-images.githubusercontent.com/38575961/226677244-8fe22cf7-e50b-436f-96a3-1d6f883b7408.jpg)

**Comment by ourongxing** [comment]
[![Deploy with Vercel](https://vercel.com/button?utm_source=busiyi&utm_campaign=oss)](https://vercel.com/new/clone?utm_source=busiyi&utm_campaign=oss&repository-url=https://github.com/ourongxing/chatgpt-vercel&env=OPENAI_API_KEY)

点这个
