### ISSUE TITLE
请问prompt在哪里找啊？

### ISSUE THREAD

**Issue by somethingforheheda** [ourongxing/chatgpt-vercel#11]
如题，还有这个预设可以自己写一个设定，直接在对话开头发给chat吗？还是说需要把写的设定设置到系统角色里？

**Comment by somethingforheheda** [comment]
我自己试着写了一个prompt，但是只是对第一句话管用，后面他就失效了，但是系统预设的比如那个小红书的风格，就可以一直有效，不知道为什么？

**Comment by tiwentichat** [comment]
https://tiwenti.chat 这里面的prompt放到设定里面应该都可以用。（我之前在微信版的chat里面做过人格设定，用它们试过。（不过我有一个问题...为啥我在vercl上搭建的，作者分享的那个vercel链接，我都打不开，但是可以搭建这啥情况兄弟遇到过吗？

**Comment by somethingforheheda** [comment]
> 

可能是没开梯子吧，没太看懂你说的意思。用vercl部署，点击visit就可以访问自己的了。如果是想访问他的，你点他发的链接就行了。

**Comment by tiwentichat** [comment]
> > 
> 
> 可能是没开梯子吧，没太看懂你说的意思。用vercl部署，点击visit就可以访问自己的了。如果是想访问他的，你点他发的链接就行了。

vercl链接确实到现在都打不开（梯子都打不开，莫名），我加了自己域名最开始打不开，过了一段时间后打开了..估计是缓存问题
