### ISSUE TITLE
他们能窃取我们的API吗？

### ISSUE THREAD

**Issue by Root-FTW** [ourongxing/chatgpt-vercel#110]
这一节代码是怎么回事？

https://github.com/Root-FTW/eva02/blob/main/src/pages/api/cron.ts#L93

他们把我们的API密钥发送到另一个不是openai官方的地方？

看起来他们是把它发送到那个网站来确认我的api是否被禁止，这是我在GitHub上看到的最不安全的事情。

我们怎么知道他们在收到我们的API时没有使用呢？

**Comment by ourongxing** [comment]
`他们` 是指的谁，这里面除了 openai 外就只有一个 push 服务商。
