### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by fssflyang** [ourongxing/chatgpt-vercel#111]
pc网页端在连续对话中，不打空格键或“/”键也会弹出Prompt 预设选择框，并且影响回车键发送消息（不会发送消息而是选择了Prompt 预设的第一项，之前打的聊天内容被替换）
小白不懂代码，希望更新一下下，非常感谢！

**Comment by ourongxing** [comment]
输入法的问题，换一个输入法试试，目前我无法重现。
