### ISSUE TITLE
作者你好，请问下我部署在本地，回答的时候没有stream的效果？

### ISSUE THREAD

**Issue by lmuiotctf** [ourongxing/chatgpt-vercel#117]
代码没有报错，nodejs是18.15的

**Comment by ourongxing** [comment]
我的可以，大概率是代理 API 不支持。

**Comment by lmuiotctf** [comment]
如果代理的api不支持，NG需要配置什么嘛

**Comment by ourongxing** [comment]
这我不太了解，建议问 chatgpt

**Comment by ourongxing** [comment]
![image](https://user-images.githubusercontent.com/48356807/226882463-025196cb-e3a3-4ff5-874a-9545b35dbf6d.png)

**Comment by ourongxing** [comment]
如果您想使用 Nginx 转发 OpenAI 的 API，并且需要开启流模式（stream），您可以按照以下步骤操作：

1. 安装 Nginx

如果您还没有安装 Nginx，请先安装它。您可以在 Ubuntu 上使用以下命令进行安装：

```
sudo apt-get update
sudo apt-get install nginx
```

2. 配置 Nginx

在 Nginx 的配置文件中，您需要添加一个新的 server 块来处理 OpenAI API 的转发。您可以使用以下命令打开配置文件：

```
sudo nano /etc/nginx/nginx.conf
```

然后，在 http 块中添加以下内容：

```
stream {
    upstream openai {
        server api.openai.com:443;
    }

    server {
        listen 443;
        proxy_pass openai;
        ssl_preread on;
    }
}
```

这将创建一个流模式的 server 块，将所有从 443 端口进入的流量转发到 OpenAI API 的服务器。ssl_preread 选项将启用 SNI（服务器名称指示），以便在转发之前检查客户端的 SSL/TLS 证书。

3. 保存并退出配置文件

按下 Ctrl+X，然后按下 Y 和 Enter 保存并退出配置文件。

4. 重新加载 Nginx

使用以下命令重新加载 Nginx，以使新的配置生效：

```
sudo systemctl reload nginx
```

现在，您可以使用您的 Nginx 服务器将所有来自 443 端口的流量转发到 OpenAI API 的服务器。

**Comment by lmuiotctf** [comment]
我用官方的api测试了，也是一样，所以应该不是反向代理的问题

**Comment by ourongxing** [comment]
你给路由器开个代理就可以了

**Comment by lmuiotctf** [comment]
具体是这样的
![1120](https://user-images.githubusercontent.com/52068443/226916126-7d2b709c-5621-4461-99c0-83565889783c.gif)

**Comment by ourongxing** [comment]
只能是网络的原因，不然 railway 也是直接 node 部署的，还是可以。

**Comment by lmuiotctf** [comment]
还有就是 pnpm dev
  🚀  astro  v2.1.3 started in 206ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

启动起来了，但是服务器ip+3000端口 会进不去
