### ISSUE TITLE
导出图片功能不能用了

### ISSUE THREAD

**Issue by allentofight** [ourongxing/chatgpt-vercel#123]

**Comment by ourongxing** [comment]
电脑上改成复制了

**Comment by allentofight** [comment]
所以导出图片后续要去掉吗，现在点击没效果

**Comment by ourongxing** [comment]
我不是说了吗，电脑上是直接把图片复制到剪贴板上。

allentofight ***@***.***> 于 2023年3月24日周五 19:07写道：

**Comment by allentofight** [comment]
了解了，之前是下载，现在复制成功没有提示我还以为出bug了，可以把提示加上
