### ISSUE TITLE
今晚更新了模型选择，但是发消息总是提示maxTokens is not defined

### ISSUE THREAD

**Issue by AitoolsPro** [ourongxing/chatgpt-vercel#131]
![image](https://user-images.githubusercontent.com/128456771/227805580-38532bb3-bdbf-4170-ac6b-8147f069fc1e.png)
今晚更新了模型选择，但是发消息总是提示maxTokens is not defined
<img width="447" alt="1679866103302" src="https://user-images.githubusercontent.com/128456771/227805662-e9e5eb62-6a86-4cfd-b991-e751ea6902e9.png">
![image](https://user-images.githubusercontent.com/128456771/227805723-1d043a2c-5d98-4790-b80a-ff4b2ed24c57.png)
![image](https://user-images.githubusercontent.com/128456771/227805809-f3b81ca7-7bdf-40f7-9334-6e1a33ae3165.png)
能想到的解决办法都是了，但是发消息就是显示maxTokens is not defined
![image](https://user-images.githubusercontent.com/128456771/227805842-0c3f64ea-2ca9-45a9-9e5f-1ce3b410ea93.png)
q求大佬帮忙解决一下，谢谢 ，十分感谢

**Comment by ourongxing** [comment]
搜一下这个词不就知道在哪里了。

**Comment by AitoolsPro** [comment]
谢谢大佬解决了
