### ISSUE TITLE
最新版本代码会出现 请求慢，回答打字卡顿的效果-+

### ISSUE THREAD

**Issue by lmuiotctf** [ourongxing/chatgpt-vercel#134]
最新版本代码会出现 请求慢，回答打字卡顿的效果-+

**Comment by ourongxing** [comment]
只能是 openai api 的问题。

**Comment by lmuiotctf** [comment]
![3f9470cf6e167b6ade12ee4bc39126a](https://user-images.githubusercontent.com/52068443/227858925-06460601-e59a-4140-b90e-99a9de641643.jpg)
界面排版好像也有这样的问题

**Comment by HimiCos** [comment]
最新版沒出現過卡頓、排版等問題
![image](https://user-images.githubusercontent.com/92566148/228091742-94fb27f7-3769-4b98-8dd8-db7357c4fec7.jpeg)
