### ISSUE TITLE
[新功能建议] 可以添加telegram的bottoken进行消息推送么

### ISSUE THREAD

**Issue by Respawn-ID** [ourongxing/chatgpt-vercel#140]
如题，这样可以更加方便且省钱的获得消息推送功能

**Comment by ourongxing** [comment]
server 酱一天可以免费推送两条，还支持 markdown。

**Comment by ourongxing** [comment]
获取余额的 api 本来就没法查到信用卡限额。

**Comment by Respawn-ID** [comment]
tdchat好像就可以咨询余额，只需要api，不知道怎么搞的= =



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月29日(周三) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ourongxing/chatgpt-vercel] [新功能建议] 可以添加telegram的bottoken进行消息推送么 (Issue #140)




 
获取余额的 api 本来就没法查到信用卡限额。
