### ISSUE TITLE
如何在vercel部署后自定义代理服务器。

### ISSUE THREAD

**Issue by moxi000** [ourongxing/chatgpt-vercel#142]
fork你的github之后，自己在vercel上进行了部署，在控制台设置了OPENAI_API_BASE_URL变量，但是仍旧无法访问（对应的key）已经修改。不想自己进行本地部署，请问该如何操作。

**Comment by ourongxing** [comment]
修改后要重新部署

**Comment by moxi000** [comment]
返回内容是：undefined is not an object (evaluating 'ie.error.message')

**Comment by ourongxing** [comment]
只能说明这个 api 的返回值格式不一样。

**Comment by moxi000** [comment]
emmmm我用python查看了返回格式是完全一样的

**Comment by ourongxing** [comment]
那我就不知道了，自己改源码
