### ISSUE TITLE
[BUG] 輸入框與發送按鈕換行後高度不一

### ISSUE THREAD

**Issue by himicoswilson** [ourongxing/chatgpt-vercel#144]
### 換行後高度不一
![CleanShot 2023-03-28 at 14 37 09@2x_副本](https://user-images.githubusercontent.com/92566148/228154964-4136852e-bf61-48c6-b801-87a54538c6a6.png)

**Comment by Ssiswent** [comment]
+1，而且手机上长按输入法Enter没有办法换行= =

**Comment by ourongxing** [comment]
就是这样设计的

**Comment by Ssiswent** [comment]
> 

请问在手机上在呢么换行呢，我用输入法自带的换行功能也没办法换行，按Enter直接就发送了= =
