### ISSUE TITLE
Gt4 api error 

### ISSUE THREAD

**Issue by boss9xy** [ourongxing/chatgpt-vercel#146]
Gt4 not working

**Comment by boss9xy** [comment]
> 你有 gpt4 的使用资格吗

![Screenshot_2023-03-29-16-26-32-32_e307a3f9df9f380ebaf106e1dc980bb6.jpg](https://user-images.githubusercontent.com/63171333/228490052-b8e905ef-07c3-4c7c-a720-aa8547ff9e8a.jpg)

**Comment by boss9xy** [comment]
> 你有 gpt4 的使用资格吗

_你有试过了没_

**Comment by ourongxing** [comment]
那给我试试，我还没有获得资格。发邮箱 orongxing@gmail.com

**Comment by boss9xy** [comment]
抱歉，我在提取代码时出了一些错。您的代码非常完美。我在副帐户中收到了一封电子邮件，从主帐户中获取了API代码。尽管主帐户已升级到Plus版本，但API 4尚未激活。非常抱歉。我将先检查我的项目的测试版本，完成后再提供给您试用。
