### ISSUE TITLE
fork后添加mysql，连接自己服务器处理数据。本地pnpm build 正常，但是git commit到vercel deploy build的时候报错

### ISSUE THREAD

**Issue by wlc002** [ourongxing/chatgpt-vercel#147]
fork后修改代码添加mysql模块，连接自己服务器处理数据。本地pnpm build 正常，但是git commit到vercel，进行 deploy build的时候报错。这是添加的模块：
"mysql": "^2.18.1",
    "solid-js": "^1.6.15",
    "util": "^0.12.5"
麻烦帮忙看看问题出在哪里？ thank u
![微信截图_20230329215333](https://user-images.githubusercontent.com/16040091/228561506-3021b193-f9c3-488d-bd02-c56f7d7762f9.png)

**Comment by Nicolasking007** [comment]
+1 我也是使用这个`crypto` 有问题

**Comment by ourongxing** [comment]
vercel 用的是 deno 环境，并不是 node。
