### ISSUE TITLE
部署到vercel怎么添加自己的key啊

### ISSUE THREAD

**Issue by qxbug** [ourongxing/chatgpt-vercel#15]
试了下fork回去 把key编辑进去再部署到vercel  openai马上就来邮件说key暴露了 把key自动换掉了

**Comment by eryajf** [comment]
fork之后，拷贝 .env ，然后注意不要往里边填任何内容，然后直接部署，部署之后，就需要在页面填写key之后才能使用。

**Comment by ourongxing** [comment]
确实有这个问题，我是本地运行 `vercel deploy` 命令的，等会我加一个 environment 变量就可以在 vercel 添加了。

**Comment by ourongxing** [comment]
现在支持了，详情看 [README](https://github.com/ourongxing/chatgpt-vercel#readme)

**Comment by tiwentichat** [comment]
请教：后台添加了 key：OPENAI_API_KEY value: sk-xxxxx，但是前台页面还是必须在设置里加一下这个key才能使用啊
那后台添加好像就没有意义了。

**Comment by tiwentichat** [comment]
（大橘好辛苦，请多给它一个罐头

**Comment by tiwentichat** [comment]
> 请教：后台添加了 key：OPENAI_API_KEY value: sk-xxxxx，但是前台页面还是必须在设置里加一下这个key才能使用啊 那后台添加好像就没有意义了。

我又回来了。。缓存问题。等、等、等、等就好了
