### ISSUE TITLE
报错fetch failed

### ISSUE THREAD

**Issue by HalfAnElephant** [ourongxing/chatgpt-vercel#151]
我已经在.env文件中设置了代理，仍然显示fetch failed
![image](https://user-images.githubusercontent.com/67222274/228978667-ef07ec52-0a1c-49a9-ae97-c6ec4a78f49f.png)
且api key有用

**Comment by ourongxing** [comment]
然而我并没有提供这个变量，也没有提供这个功能，建议直接路由器翻墙或者用代理 API。
