### ISSUE TITLE
右上角的功能按钮会挡住文字，导致无法选中复制底下的文字

### ISSUE THREAD

**Issue by MC-dusk** [ourongxing/chatgpt-vercel#153]
右上角的功能按钮会挡住文字，导致无法选中复制底下的文字

简单的解决办法，大概如果把文字整体下移一行就好了，当然也有很多种其他解决办法，临时解决办法就是复制全文出来再选。

![image](https://user-images.githubusercontent.com/52311860/229062558-80ea7dd0-4bf6-4a05-9082-71cd1c29872a.png)

**Comment by ourongxing** [comment]
你是在逗我吗，鼠标非得刚好放在字上边才能复制？

**Comment by MC-dusk** [comment]
挡住了怎么选中？我只要复制挡住的部分的特定几个字，应该说的很明白，如果有什么我不知道的方法，务必赐教

**Comment by ourongxing** [comment]
选中的时候鼠标是可以往下拉，直接换行的。。。
