### ISSUE TITLE
查询余额报错

### ISSUE THREAD

**Issue by allentofight** [ourongxing/chatgpt-vercel#159]

**Comment by popdo** [comment]
余额查询官网改规则了，需要会话密钥来进行访问

**Comment by TsingYi1263** [comment]
+1
Cannot read properties of undefined (reading 'toFixed')

**Comment by ourongxing** [comment]
之前的查询接口用不了了，现在只能查到用了多少，连总的额度都查不到。之后有空在改吧。

**Comment by TsingYi1263** [comment]
> 之前的查询接口用不了了，现在只能查到用了多少，连总的额度都查不到。之后有空在改吧。

我改好了，拉取请求一下
