### ISSUE TITLE
本地部署一直警告 warnings：

### ISSUE THREAD

**Issue by souce-xu** [ourongxing/chatgpt-vercel#166]
warnings
  Some items were passed to additionalManifestEntries without revisioning info. This is generally NOT safe. Learn more at https://bit.ly/wb-precache.
  - /404

  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/Users/xuwei/Downloads/agpt/chatgpt-vercel/dev-dist",
  "globPattern": "**/*.{css,js,html,svg,png,ico,txt}",
  "globIgnores": [
    "**/node_modules/**/*",
    "sw.js",
    "workbox-*.js"
  ]
}

**Comment by ourongxing** [comment]
正常
