### ISSUE TITLE
自己弄好多细节不会，弄了个交流群，大家技术讨论 加connection-image 我来拉你

### ISSUE THREAD

**Issue by yyx20202020** [ourongxing/chatgpt-vercel#169]
自己搞好多细节不清楚的，一起来弄吧。。搞个部署问题的解决文档出来 一步一步点哪儿那种 有群交流反馈更快点。。

**Comment by yyx20202020** [comment]
VX: connection-image 备注：GPT搭建

**Comment by Lucoding00** [comment]
弄个qq群呗

**Comment by azz212** [comment]
424179700

**Comment by TsingYi1263** [comment]
能解决余额查询接口的修改吗

**Comment by TsingYi1263** [comment]
> 自己搞好多细节不清楚的，一起来弄吧。。搞个部门问题的解决文档出来 一步一步点哪个孩子那种有群交流反应更快点。。
能解决余额查询接口的修改吗

**Comment by TsingYi1263** [comment]
> 自己搞好多细节不清楚的，一起来弄吧。。搞个部署问题的解决文档出来 一步一步点哪儿那种 有群交流反馈更快点。。

能解决余额查询接口的修改吗
