### ISSUE TITLE
一个其他的问题请教啊

### ISSUE THREAD

**Issue by xingstarx** [ourongxing/chatgpt-vercel#186]
大佬我想要请教给问题啊：
就是我添加了MongoDB的依赖，然后呢，我部署到vercel上面，结果编译就报错，提示我存在一个ip库，其实我都没有用到它呢

用的是`pnpm install mongodb` 添加的呢

![image](https://user-images.githubusercontent.com/8245264/231467131-264250cf-07b2-4570-bfb2-64d7200fbfc4.png)

我用`npm ls` 也查不到ip这个库是怎么被依赖到node_modules里面的啊。

能给点指点嘛，感觉都找不到相关的资料，英文的也没搜到，大佬能给点提示吗

**Comment by ourongxing** [comment]
vecel 是 deno 环境，不兼容部分 node 的库，本来也只是轻量的，最多请求下 API。
