### ISSUE TITLE
为啥在 vercel 的环境变量里设置了PASSWORD，网站不用密码还能访问？

### ISSUE THREAD

**Issue by zhouwei713** [ourongxing/chatgpt-vercel#191]
哪位大佬知道，帮忙解答以下呀
![image](https://user-images.githubusercontent.com/12554051/232313856-ddead6ca-4128-4fa3-bc7a-3e20c38d38ec.png)

**Comment by vincentkenny66** [comment]
同问，我设置了密码还是可以登录就可以访问，还要就是我把CHATGPT-KEY删除了，还是可以继续使用。这是什么情况？难道可以不要token了？哪位大佬解答下。

**Comment by ourongxing** [comment]
确实是 bug

**Comment by ourongxing** [comment]
下一次部署时生效

**Comment by 973440710** [comment]
重新部署了，还是没生效

**Comment by ourongxing** [comment]
无法重现

**Comment by zhouwei713** [comment]
是的，需要重新部署，谢谢
