### ISSUE TITLE
【bug】markdown代码块解析异常，shell“#”字符注释解析成标题了

### ISSUE THREAD

**Issue by JeazW** [ourongxing/chatgpt-vercel#195]
![image](https://user-images.githubusercontent.com/75829171/232678350-adefdb0d-0864-4311-865d-1e4a40a66432.png)

**Comment by ourongxing** [comment]
那是因为它没有用代码块包起来

**Comment by JeazW** [comment]
了解

**Comment by ourongxing** [comment]
![image](https://user-images.githubusercontent.com/48356807/232679615-56884097-15da-4bbe-b606-a548b62813b6.png)

**Comment by JeazW** [comment]
麻烦大佬了，我测出来了，多谢多谢

**Comment by JeazW** [comment]
请问默认黑色主题在哪个文件改，我知道这种最好不要麻烦作者，可是我实在没找到位置。。。😂，还得麻烦您贴个文件名

**Comment by ourongxing** [comment]
> 请问默认黑色主题在哪个文件改，我知道这种最好不要麻烦作者，可是我实在没找到位置。。。😂，还得麻烦您贴个文件名

https://github.com/ourongxing/chatgpt-vercel/blob/95ce3517aa96f86899e4d1aa2803304d05b0aec7/src/root.tsx#L18

是代码高亮吗

**Comment by JeazW** [comment]
谢谢，就是打开页面后默认的主题样式，现在是明亮，我想自定义成dark

**Comment by ourongxing** [comment]
> 谢谢，就是打开页面后默认的主题样式，现在是明亮，我想自定义成dark

默认跟随系统

**Comment by ourongxing** [comment]
https://github.com/ourongxing/chatgpt-vercel/blob/4d1342fd3ac329e20dbbc24f31493bbdd0361ab4/src/entry-client.tsx#L4

```js
const e = localStorage.getItem(LocalStorageKey.THEME) || "dark" 
```

**Comment by JeazW** [comment]
好的，收到！！
