### ISSUE TITLE
添加某度统计

### ISSUE THREAD

**Issue by Greysonzs** [ourongxing/chatgpt-vercel#196]
麻烦问一下我如果需要添加某度统计 应该将代码放置在哪里呢

**Comment by ourongxing** [comment]
https://github.com/ourongxing/chatgpt-vercel/blob/main/src/entry-client.tsx

加到里面就行

**Comment by Greysonzs** [comment]
感谢大佬回复

**Comment by Greysonzs** [comment]
![image](https://user-images.githubusercontent.com/127030540/233648077-45dbe942-86f0-41f6-9a7d-645c46437dfb.png)
可以直接这样放吗？

**Comment by ourongxing** [comment]
不要 <script>
