### ISSUE TITLE
回答問題後輸入"繼續"，會把"繼續" 當成新問題來回答

### ISSUE THREAD

**Issue by Lawlietr** [ourongxing/chatgpt-vercel#2]
你的有這問題，diu 的可以針對原問題"繼續"回答

**Comment by ourongxing** [comment]
需要自己打开 `开启连续对话`

**Comment by ourongxing** [comment]
然后默认会有一个 `系统角色指令`，每次都会添加 `回答要尽可能的客观，不知道就说不知道，不要乱答。`，可能会干扰 `继续` 指令
