### ISSUE TITLE
感谢大佬添加了页面自动滚动，但手机上访问时最下面的回答会被手机键盘覆盖

### ISSUE THREAD

**Issue by xxqq170** [ourongxing/chatgpt-vercel#21]
![image](https://user-images.githubusercontent.com/115010355/223404427-10650f6f-92fe-4032-98cb-482b9509c5fd.png)
如图，最下面的回答被键盘覆盖。感谢大佬感谢大佬，真不是找茬

**Comment by ourongxing** [comment]
没办法，现在加了个点击输入框自动滑到底部
