### ISSUE TITLE
[UI] 建议「思维发散程度」条增加数值展示

### ISSUE THREAD

**Issue by GOWxx** [ourongxing/chatgpt-vercel#22]
现在的范围条的两边数值和当前数值都是不清楚的，
操作是方便的，但含义是模糊的。

期望增加两端数值展示或当前数值展示。

![image](https://user-images.githubusercontent.com/12870715/223405944-ec374706-b80e-4bc9-97a1-da64a51c307a.png)

**Comment by ourongxing** [comment]
已添加
