### ISSUE TITLE
希望可以融合ayaka14732/ChatGPTAPIFree

### ISSUE THREAD

**Issue by mmwong1984** [ourongxing/chatgpt-vercel#227]
可以用所謂的API端點：https://free.churchless.tech/v1/chat/completions
就是像CF反代一樣
但是不要輸入任何的API碼就可以取得Chatgpt回答的內容

**Comment by ClarenceDan** [comment]
然后网站就被人当成免费API源来使用了

**Comment by mmwong1984** [comment]
你是觉得这个意见好还是不好

**Comment by mmwong1984** [comment]
其实现在使用官方的指引是可以的，但是在很多专案都是不能使用这种方法。可能是因为需要验证API
