### ISSUE TITLE
免費 ChatGPT Api: FoxGPT / gpt

### ISSUE THREAD

**Issue by mmwong1984** [ourongxing/chatgpt-vercel#228]
這個不知道什麽東西可以提供類似免費的API
OPENAI_API_BASE_URL: https://api.hypere.app/v1/
OPENAI_API_KEY: 去 https://discord.com/invite/E8E2TnE75D 生成 （記住先去🔒認證才去#bot生成代碼）

**Comment by mmwong1984** [comment]
這不能用......
Yidadaa/ChatGPT-Next-Web 經測試可以用

**Comment by ENVYOVERLOXD** [comment]
如何去使用bot给的key?

**Comment by mmwong1984** [comment]
> 如何去使用bot给的key?

Yidadaa/ChatGPT-Next-Web 才可以用
不可以在這個項目使用
BASE_URL
https://api.hypere.app/
OPENAI_API_KEY
bot给的key

**Comment by ENVYOVERLOXD** [comment]
谢谢.还有个叫anse的项目也可以直接用.不用去配置环境变量

**Comment by ENVYOVERLOXD** [comment]
这个key有限额吗?

**Comment by mmwong1984** [comment]
> 这个key有限额吗?

每天30000
