### ISSUE TITLE
可以增加一个new chat的选项吗

### ISSUE THREAD

**Issue by pang-xiang** [ourongxing/chatgpt-vercel#23]
希望可以保存某些历史对话

**Comment by eryajf** [comment]
如果遇到精彩的对话，欢迎保留在这里 https://github.com/eryajf/awesome-chatgpt-answer

**Comment by ysjiang4869** [comment]
vote +1, 感觉距离一个完美工具只差两个功能：
- 支持多对话
- 能支持一个webdav 同步 或者json导入导出的功能就好了。这样可以多设备保存记录。

**Comment by ysjiang4869** [comment]
需要的可以临时部署我fork后修改的，支持多chat（在url中新增#chatName创建chat)，切换chat，删除chat。
我是后端开发，所以功能上可能没有那么优雅。
目前暂未完成的：修改chatName, newChatButton
