### ISSUE TITLE
回答问题出现乱码 如何修复

### ISSUE THREAD

**Issue by fuzipei** [ourongxing/chatgpt-vercel#234]
![image](https://github.com/ourongxing/chatgpt-vercel/assets/96692326/4aaf6dc7-9af8-4ffe-b515-2d229a15462d)

**Comment by ourongxing** [comment]
<img width="707" alt="image" src="https://github.com/ourongxing/chatgpt-vercel/assets/48356807/cbe77623-727d-4a42-994c-a83cdf2574fb">

调小一点
