### ISSUE TITLE
建议加上”支持更长上下文的gpt-3.5.turbo-16k模型"

### ISSUE THREAD

**Issue by ZS629** [ourongxing/chatgpt-vercel#237]
建议在现有的模型列表中加入支持更长上下文的功能，这将使得模型能够更好地理解和处理更复杂的语言结构。这一功能的加入将大大提升模型的性能和实用价值。希望能够认真考虑并尽快实现这一建议。谢谢！

[OpenAI支持最新gpt-3.5-turbo-16k等模型](https://platform.openai.com/docs/models/continuous-model-upgrades)

**Comment by ourongxing** [comment]
已添加
