### ISSUE TITLE
Spanish translation to documents and strings

### ISSUE THREAD

**Issue by johnfelipe** [ourongxing/chatgpt-vercel#238]
I want to collaborate
Pls Téllez me Wich path need to translate to Spanish

**Comment by ourongxing** [comment]
Thank you very much. Please wait for me to complete i18n of web

**Comment by johnfelipe** [comment]
Hi dear any progress for i18n?

**Comment by ourongxing** [comment]
Sorry, I have no time for this project and it's just for Chinese. Maybe you can use https://github.com/Yidadaa/ChatGPT-Next-Web for a better experience。Don't waste your time for it.
