### ISSUE TITLE
初次请求后,首页文字不加载,加载速度会很慢

### ISSUE THREAD

**Issue by LuoFanA595** [ourongxing/chatgpt-vercel#243]
本服务仅提供ChatGPT转发。
点击每条消息前的头像，可以锁定对话，作为角色设定。
支持多个对话模式，打开对话设置，点击新建对话。
在输入框里输入 // 或者 空格空格 可以切换对话，搜索历史消息。
Shift + Enter 换行。开头输入 / 或者 空格 搜索 Prompt 预设。↑ 可编辑最近一次提问。点击顶部名称滚动到顶部，点击输入框滚动到底部。

以上信息初次请求后,网页上不显示,需要等很长一段时间或重复请求才可以!

**Comment by kujoujo** [comment]
关于台湾乡土文化开题报告

**Comment by kujoujo** [comment]
关于台湾乡土文化开题报告
