### ISSUE TITLE
输入中文字符后回车，不会触发发送操作而是选中第一条提示填入输入框。

### ISSUE THREAD

**Issue by 5700pgf** [ourongxing/chatgpt-vercel#26]
英文字符没有这个现像

**Comment by ourongxing** [comment]
不太懂什么意思，不应该就是这个逻辑吗

**Comment by 5700pgf** [comment]
可能是每个人的使用习惯不同，按我理解是在问题框那里输入内容，然后按回车发送问题（我没有用“/”开头），但现在的情况是我输入内容后按回车，会自动把我输入的内容清掉，然后填入提示的第一条，也就是说我输入内容后还要去用鼠标点一下发送按钮，才能发送问题，我认为这样操作不是很方便。

**Comment by ourongxing** [comment]
prompt 提示只会在开头输入空格或者 / 的时候弹出

**Comment by 5700pgf** [comment]
你这一说我就明白，我以为你改了提示的唤出方式，我用的黄狗五笔，只要输入中文，就会一直显示prompt 提示，换了系统自带的五笔就正常了。
