### ISSUE TITLE
新版本速度问题

### ISSUE THREAD

**Issue by Lucoding00** [ourongxing/chatgpt-vercel#28]
更新到最新版本之后，相应的速度下降了不少，我还是回退到之前部署的版本上面了

**Comment by zzzqu** [comment]
同有这个问题，比之前慢好多

**Comment by Lucoding00** [comment]
之前版本挺快的

**Comment by Lucoding00** [comment]
> 是这个原因吗，难道不是 API 本身慢了吗

我重新回退到之前的版本，就比新版本快很多

**Comment by ourongxing** [comment]
> > 是这个原因吗，难道不是 API 本身慢了吗
> 
> 我重新回退到之前的版本，就比新版本快很多

你多试几次，现在普遍都慢了

**Comment by Lucoding00** [comment]
> > > 是这个原因吗，难道不是 API 本身慢了吗
> > 
> > 
> > 我重新回退到之前的版本，就比新版本快很多
> 
> 你多试几次，现在普遍都慢了

那好吧

**Comment by ourongxing** [comment]
![Screenshot_20230308-111151.jpg](https://user-images.githubusercontent.com/48356807/223610244-7c46f0af-8eb4-4121-bab1-e1b5e6f1aef0.jpg)

**Comment by Lucoding00** [comment]
> ![Screenshot_20230308-111151.jpg](https://user-images.githubusercontent.com/48356807/223610244-7c46f0af-8eb4-4121-bab1-e1b5e6f1aef0.jpg)
好的
