### ISSUE TITLE
在vecel搭建的，搭好了，访问失败。。然后作者的预览链接也打不开。。但是搭建过程没问题啊

### ISSUE THREAD

**Issue by tiwentichat** [ourongxing/chatgpt-vercel#34]
这这这...啥情况，应该不是tizi问题，不然也不能搭建啊
有大佬出来帮解答一下不

**Comment by tiwentichat** [comment]
> 我写的很清楚，vercel.app 域名被墙，需要用自己的域名才可以直接访问。

我是魔法上网啊，也打不开吗（😱而且我刚才添加了域名，我再刷新一下试试，感谢！

**Comment by Lucoding00** [comment]
你有阿里云的云DNS解析么
