### ISSUE TITLE
我填了key，为什么还是这样啊

### ISSUE THREAD

**Issue by 46135413** [ourongxing/chatgpt-vercel#35]
[POST] /api/stream reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

**Comment by ourongxing** [comment]
key 填错了吧

**Comment by zengyunda** [comment]
这个问题我也遇到过，是因为vercel请求ChatGPT超过了5秒没有返回结果，那边会直接报504

**Comment by dofine** [comment]
同样遇到过这个问题，之前用的账号是某宝买的，可能有问题。自己注册了一个新号部署就正常了。
