### ISSUE TITLE
如果设置了对话记录缓存，当页面字数超过一定的数量，后面的问题就无法显示了

### ISSUE THREAD

**Issue by allentofight** [ourongxing/chatgpt-vercel#49]
如果我设置了对话记录缓存，当页面字数超过一定的数量，后面的问题就无法显示了，页面有字数限制但是又没有自动清除前面的对话记录，看起来像服务挂了

<img width="342" alt="WechatIMG28" src="https://user-images.githubusercontent.com/1235483/224227665-e6dd0c90-1d7c-459b-ace0-9605c3c8e7e3.png">

**Comment by ourongxing** [comment]
你这样式都没加载出来

**Comment by allentofight** [comment]
> 你这样式都没加载出来

样式加载出来也是有这个问题的，貌似是触发了 4096 的 token？因为开启连续会话的话会把所有的对话都传过去，这个也是消耗 token 的吧?
