### ISSUE TITLE
希望增加删除单条问答记录的功能

### ISSUE THREAD

**Issue by NoColor96** [ourongxing/chatgpt-vercel#51]
在需要连续对话的场景，有时一些历史消息是我们不需要提供给api的。目前只有清除整个消息记录的功能，需要携带部分上下文时就满足不了需求了。希望大佬加下

**Comment by kjgcadsofz** [comment]
对啊，希望可以清楚部分的对话记录，比如单条的。

**Comment by GOWxx** [comment]
在导出时，也想通过 删除无用对话 或 选择指定对话 的方式，过滤掉不想要的内容。
