### ISSUE TITLE
开启多会话模式报错问题

### ISSUE THREAD

**Issue by xiaoxin6666666** [ourongxing/chatgpt-vercel#53]
setSetting({
      ...defaultSetting,
      ...parsed
      continuousDialogue: false
    })

取消注释之后vercel这边上传报错是什么原因

**Comment by xiaoxin6666666** [comment]
![7`FMYQ`DH(X(42B(}IU5}LK](https://user-images.githubusercontent.com/110280319/224447008-a6bb4bd3-a4aa-4abd-8f24-ce223a157208.png)

**Comment by xiaoxin6666666** [comment]
> ![7FMYQDH(X(42B(}IU5}LK](https://user-images.githubusercontent.com/110280319/224447008-a6bb4bd3-a4aa-4abd-8f24-ce223a157208.png)

修改上传就显示这个咋解决呢

**Comment by ourongxing** [comment]
你是完全不懂啊，没加逗号

**Comment by xiaoxin6666666** [comment]
> 你是完全不懂啊，没加逗号

setSetting({
  ...defaultSetting,
  ...parsed,
  continuousDialogue: false
})

是这样吗，这样我加过了还是一样

**Comment by xiaoxin6666666** [comment]
> 你是完全不懂啊，没加逗号

setSetting({
  ...defaultSetting,
  ...parsed,
  continuousDialogue: false
})

false要改True不

**Comment by xiaoxin6666666** [comment]
> 你是完全不懂啊，没加逗号

明白了我逗号没搞对

**Comment by xiaoxin6666666** [comment]
> > 你是完全不懂啊，没加逗号
> 
> 明白了我逗号没搞对

大佬加了角色命令为啥不能追问了呀

**Comment by ourongxing** [comment]
> > > 你是完全不懂啊，没加逗号
> > 
> > 明白了我逗号没搞对
> 
> 大佬加了角色命令为啥不能追问了呀

角色命令是加到你每句话的前面的，可能会干扰，自己改一下你的指令。
