### ISSUE TITLE
输入中文时，输入法的空格选字会被错误识别为开启prompt提示

### ISSUE THREAD

**Issue by Rackar** [ourongxing/chatgpt-vercel#58]
导致连续中文打字后，一回车发现自己的输入被默认的prompt提示词给覆盖了。

**Comment by Rackar** [comment]
更正，不是空格，是一开始输入就会展开

https://user-images.githubusercontent.com/18388400/224517845-89e037a3-67cb-44f0-b0de-8ea82b121bc8.mp4

**Comment by ourongxing** [comment]
输入法的问题，我的输入法就不会这样。

**Comment by qqiuqingx** [comment]
我用小狼毫输入法也会出现这样的情况
