### ISSUE TITLE
Since it is a variant project of fork, why did you remove the fork?

### ISSUE THREAD

**Issue by yzh990918** [ourongxing/chatgpt-vercel#59]
I am the maintainer of the [chatgpt-demo](https://github.com/ddiu8081/chatgpt-demo) . I suggest you don't violate the open source agreement, try add a fork tag to the secondary development. Thanks

**Comment by ourongxing** [comment]
首先，现在 readme 还写着基于 chatgpt-demo 开发，license 里还加了 diu。

其次，没有那条协议写着不能将 fork 仓库转为独立仓库。开发方向不同转为独立项目继续开发很正常吧。
