### ISSUE TITLE
网页不能自动下滑，要手动翻页

### ISSUE THREAD

**Issue by xxqq170** [ourongxing/chatgpt-vercel#6]
![image](https://user-images.githubusercontent.com/115010355/223112858-01f4789a-086c-4c9b-a9bd-58c6fcb8bc41.png)
感谢大佬的教程和增强版

**Comment by 5700pgf** [comment]
ddiu8081/chatgpt-demo  那边已经实现在自动滚动的功能，烦请优化一下

**Comment by zzzqu** [comment]
+1，希望可以有这个功能，很好用

**Comment by ourongxing** [comment]
已添加
