### ISSUE TITLE
可否实现通过传递 URL 查询参数打开直接发送第一个问题

### ISSUE THREAD

**Issue by lucianl** [ourongxing/chatgpt-vercel#63]
这样就可以方便用 Alfred、Raycast 这类工具快捷地输入问题然后打开并提问了

**Comment by ourongxing** [comment]
建议直接使用他们自带的插件

**Comment by lucianl** [comment]
研究了一下，我自行实现了，效果如图：

![Jietu20230313-232540-HD](https://user-images.githubusercontent.com/6085733/224813042-eff116c6-c1af-41ba-9aec-a80927d19f6c.gif)
