### ISSUE TITLE
HTML渲染bug污染原有样式

### ISSUE THREAD

**Issue by youhunwl** [ourongxing/chatgpt-vercel#64]
返回 HTML 的回答如果含有css 样式会污染原有页面。
例如问题：写一个登录网页
[![ppQzzSf.png](https://s1.ax1x.com/2023/03/13/ppQzzSf.png)](https://imgse.com/i/ppQzzSf)

**Comment by ourongxing** [comment]
但是这个问题的关键还是 html 代码没有用代码块包起来，html 标签还是有用的。

**Comment by ourongxing** [comment]
算了我装个插件吧
