### ISSUE TITLE
请问能不能使用更加合理的方案实现连续对话

### ISSUE THREAD

**Issue by cakexxx** [ourongxing/chatgpt-vercel#75]
现有的连续对话方案既浪费token，又占用字符数，请问能不能使用新的方案实现连续对话，比如在网页端使用的方案，这是我在网上看到的一些人的讨论，希望可以给您一些参考[https://hu60.cn/q.php/bbs.topic.104621.html](https://hu60.cn/q.php/bbs.topic.104621.html)

**Comment by lanshao520** [comment]
我也期待使用更合理的方案实现，我不在乎token但是问几句就会提示超过4096个字符不能提交了，其实大部分都是一些没用的记录也传过去了 最好是让用户选择需要需要保留那些或者记录过多的话自动清除前面的
