### ISSUE TITLE
vercel部署自定义域名界面加载不完全，Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by Exisi** [ourongxing/chatgpt-vercel#76]
原有vercel域名可以访问，控制台不报错，用自定义域名访问就报错下面的错误

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
    at Generator.8679dc2f.js:10:681

似乎是界面没加载出来，输入框没了

**Comment by Exisi** [comment]
现在似乎又可以访问了，我域名托管在cloudflare上，应该是 cloudflare CDN 问题

**Comment by JinChengneng** [comment]
我也一直在重复出现这个问题，请问是否有解决办法？

**Comment by Exisi** [comment]
vercel部署我放弃了，cloudflare代理问题不好解决。
因为netlify还没被墙，我暂时部署到了netlify，在cloudflare关闭代理，自定义域名暂时可以用了
不过不保证netlify的域名以后会不会像vercel一样DNS被污染
