### ISSUE TITLE
  发现一个问题，提示词显示不全，无法预览到全部提示词。

### ISSUE THREAD

**Issue by daheitian** [ourongxing/chatgpt-vercel#77]
刚才刷了下 点击空格只能显示一半提示词

**Comment by ourongxing** [comment]
避免出现性能问题，需要预览全部 prompts 请查看 https://github.com/ourongxing/chatgpt-vercel/blob/main/prompts.md

**Comment by daheitian** [comment]
没有办法在界面上解开限制吗？
