### ISSUE TITLE
建议可以将对话框内预设的prompts列表只显示##后的角色标签名即可

### ISSUE THREAD

**Issue by wrxx2019** [ourongxing/chatgpt-vercel#81]
建议可以将对话框内预设的prompts列表只显示##后的角色标签名即可，无需将整段prompts内容全部显示，点击角色标签后再发送具体对应prompts内容到对话。这样对话框看起来更简洁美观，也能更节省资源。如图所示：
![image](https://user-images.githubusercontent.com/44341143/225832015-efa4e911-ee97-4a06-a5b3-6dd29378d0e4.png)

**Comment by ourongxing** [comment]
就是这样设计的，因为搜索会匹配正文。
