### ISSUE TITLE
希望增加简单的访问控制

### ISSUE THREAD

**Issue by eryajf** [ourongxing/chatgpt-vercel#9]
是否可以加一个简单的访问控制，校验一个密码，通过之后才能访问

**Comment by Lucoding00** [comment]
> 是否可以加一个简单的访问控制，校验一个密码，通过之后才能访问

他这个网站只是一个演示模板，真正的key还是你自己生成的，权限在自己手上

**Comment by ariesy** [comment]
增加用户名密码访问控制更方便一点，如果发现流量异常，可以直接修改用户名密码的配置，不用重新去generate API key。使用用户名密码的方式也更方便分享给朋友使用。

**Comment by hezhongtang** [comment]
同意，如果能在进入的时候输入简易口令其实也是可以的，比如弹出一个窗口，输入密令后才可继续问问题。毕竟在多平台环境下不可能自己到处复制api key来问问题。

**Comment by Lucoding00** [comment]
那你的key是不是需要保存下来，保存在哪里呢，是否存在key泄露的问题呢

**Comment by ariesy** [comment]
部署的时候放环境变量就好了

**Comment by Lucoding00** [comment]
> 部署的时候放环境变量就好了

可以的，你可以切一个分支出来完成这个需求，但是我觉得复制key和复制密钥没有什么两样

**Comment by whenk7** [comment]
环境变量放一个密码，进入网页弹框输入密码

**Comment by Hime-Hina** [comment]
我记得chatgpt-demo就有这功能吧。

**Comment by wrxx2019** [comment]
> 我记得chatgpt-demo就有这功能吧。
SITE_PASSWORD这个环境变量似乎无效
chatgpt-demo下有password.astro控制，所以SITE_PASSWORD可用

**Comment by kjcx100** [comment]
> > 我记得chatgpt-demo就有这功能吧。
> > SITE_PASSWORD这个环境变量似乎无效
> > chatgpt-demo下有password.astro控制，所以SITE_PASSWORD可用

佬们知道咋更新过来不，

**Comment by wrxx2019** [comment]
> > > 我记得chatgpt-demo就有这功能吧。
> > > SITE_PASSWORD这个环境变量似乎无效
> > > chatgpt-demo下有password.astro控制，所以SITE_PASSWORD可用
> 
> 佬们知道咋更新过来不，

你看一下更新的readme, 大佬已经加了PASSWORD变量了，能设置网站密码了。
